# Config for mirror-mouse_split example dataset used in unit tests.
# For field descriptions see `config_default_multiview.yaml` in this directory.

data:
  image_resize_dims:
    width: 256
    height: 256
  #   Demo data resides in the git repo. LP_ROOT_PATH resolves to the absolute
  #   path of the lightning-pose git repo.
  data_dir: ${LP_ROOT_PATH:}/data/mirror-mouse-example_split
  video_dir: ${data.data_dir}/videos
  csv_file:
    - top.csv
    - bot.csv
  view_names:
    - top
    - bot
  num_keypoints: 7
  keypoint_names:
    - paw1LH
    - paw2LF
    - paw3RF
    - paw4RH
    - tailBase
    - tailMid
    - nose
  mirrored_column_matches:
    - [0, 1, 2, 3, 4, 5, 6]
  columns_for_singleview_pca: [0, 1, 2, 3, 4, 5, 6]

training:
  imgaug: dlc
  train_batch_size: 16
  val_batch_size: 16
  test_batch_size: 16
  train_prob: 0.8
  val_prob: 0.1
  train_frames: 1
  num_gpus: 1
  early_stop_patience: 3
  unfreezing_epoch: 20
  min_epochs: 300
  max_epochs: 300
  log_every_n_steps: 1
  check_val_every_n_epoch: 10
  rng_seed_data_pt: 42
  rng_seed_model_pt: 44
  optimizer: Adam
  optimizer_params:
    learning_rate: 1e-3
  lr_scheduler: multisteplr
  lr_scheduler_params:
    multisteplr:
      milestones: [150, 200, 250]
      gamma: 0.5

model:
  losses_to_use: ["pca_multiview"]
  backbone: resnet50_animal_ap10k
  model_type: heatmap
  heatmap_loss_type: mse
  model_name: my_base_toy_model

dali:
  base:
    train:
      sequence_length: 16
    predict:
      sequence_length: 64
  context:
    train:
      batch_size: 6
    predict:
      sequence_length: 64

losses:
  pca_multiview:
    log_weight: 10.7
    components_to_keep: 3
    epsilon: null
  pca_singleview:
    log_weight: 10.7
    components_to_keep: 0.99
    epsilon: null
  temporal:
    log_weight: 10.7
    epsilon:
      [
        12.9,
        11.3,
        10.5,
        12.0,
        5.0,
        7.3,
        0.7,
        61.8,
        11.2,
        9.9,
        9.7,
        10.1,
        4.8,
        4.9,
        1.0,
        19.2,
        6.8,
      ]
    prob_threshold: 0.05

eval:
  predict_vids_after_training: true
  save_vids_after_training: true
  test_videos_directory: ${data.video_dir}
  confidence_thresh_for_vid: 0.9

callbacks:
  anneal_weight:
    attr_name: total_unsupervised_importance
    init_val: 0.0
    increase_factor: 0.01
    final_val: 1.0
    freeze_until_epoch: 0
