# Config for ibl-paw dataset in original
# Lightning Pose publication (Biderman, Whiteway et al., Nat Methods 2024).
# For field descriptions see `config_default.yaml` in this directory.

data:
  image_resize_dims:
    height: 128
    width: 128
  data_dir: /home/zeus/content/data/ibl-paw
  video_dir: /home/zeus/content/data/ibl-paw/videos
  csv_file: CollectedData.csv
  num_keypoints: 2
  keypoint_names:
    - paw_l
    - paw_r
  columns_for_singleview_pca: [0, 1]

training:
  imgaug: dlc
  train_batch_size: 32
  val_batch_size: 128
  test_batch_size: 128
  train_prob: 0.8
  val_prob: 0.1
  train_frames: 1
  num_gpus: 1
  early_stop_patience: 3
  unfreezing_epoch: 20
  min_epochs: 300
  max_epochs: 750
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  rng_seed_data_pt: 0
  rng_seed_model_pt: 0
  optimizer: Adam
  optimizer_params:
    learning_rate: 1e-3
  lr_scheduler: multisteplr
  lr_scheduler_params:
    multisteplr:
      milestones: [150, 200, 250]
      gamma: 0.5

model:
  losses_to_use: []
  backbone: resnet50_animal_ap10k
  model_type: heatmap
  heatmap_loss_type: mse
  model_name: rebuttal23a

dali:
  base:
    train:
      sequence_length: 64
    predict:
      sequence_length: 192
  context:
    train:
      batch_size: 32
    predict:
      sequence_length: 192

losses:
  pca_singleview:
    log_weight: 10.7
    components_to_keep: 0.99
    epsilon: null
  temporal:
    log_weight: 10.7
    epsilon: 10.0
    prob_threshold: 0.05

eval:
  predict_vids_after_training: true
  save_vids_after_training: false
  test_videos_directory: ${data.video_dir}
  confidence_thresh_for_vid: 0.9

callbacks:
  anneal_weight:
    attr_name: total_unsupervised_importance
    init_val: 0.0
    increase_factor: 0.01
    final_val: 1.0
    freeze_until_epoch: 0
