"""Test the recommend CLI command argument parsing."""

import argparse
from unittest.mock import patch

import pytest

from lightning_pose.cli.commands.recommend import (
    _resolve_output_path,
    get_parser,
    handle,
)


class TestGetParser:
    """Test the get_parser function."""

    def test_returns_argument_parser(self):
        """Returns an ArgumentParser instance."""
        assert isinstance(get_parser(), argparse.ArgumentParser)

    def test_prog_is_litpose_recommend(self):
        """Returned parser has prog set to 'litpose recommend'."""
        assert get_parser().prog == 'litpose recommend'


class TestRecommendParser:
    """Test the recommend subcommand argument parsing."""

    def test_valid_args(self, parser, tmp_path):
        args = parser.parse_args(['recommend', str(tmp_path)])
        assert args.dataset_path == tmp_path
        assert args.output is None

    def test_output_flag(self, parser, tmp_path):
        output = tmp_path / 'my_config.yaml'
        args = parser.parse_args(['recommend', str(tmp_path), '--output', str(output)])
        assert args.output == output

    def test_missing_dataset_path_exits(self, parser):
        with pytest.raises(SystemExit):
            parser.parse_args(['recommend'])


class TestResolveOutputPath:
    """Test the function _resolve_output_path."""

    def test_default_when_no_config_exists(self, tmp_path):
        result = _resolve_output_path(tmp_path, None)
        assert result == tmp_path / 'config.yaml'

    def test_default_when_config_exists_uses_timestamp(self, tmp_path):
        (tmp_path / 'config.yaml').touch()
        result = _resolve_output_path(tmp_path, None)
        assert result != tmp_path / 'config.yaml'
        assert result.parent == tmp_path
        assert result.name.startswith('config_')

    def test_explicit_directory_output(self, tmp_path):
        out_dir = tmp_path / 'out'
        out_dir.mkdir()
        result = _resolve_output_path(tmp_path, out_dir)
        assert result == out_dir / 'config.yaml'

    def test_explicit_file_output(self, tmp_path):
        out_file = tmp_path / 'custom.yaml'
        result = _resolve_output_path(tmp_path, out_file)
        assert result == out_file

    def test_dataset_path_is_a_file(self, tmp_path):
        csv_file = tmp_path / 'labels.csv'
        csv_file.touch()
        result = _resolve_output_path(csv_file, None)
        assert result == tmp_path / 'config.yaml'


class TestHandle:
    """Test the handle function."""

    def _make_args(self, dataset_path, output=None):
        return argparse.Namespace(dataset_path=dataset_path, output=output)

    def test_handle_writes_config(self, tmp_path):
        from lightning_pose.utils import recommender

        analysis = recommender.DatasetAnalysis(
            dataset_path=tmp_path,
            data_dir=tmp_path,
            csv_paths=[tmp_path / 'CollectedData.csv'],
            view_names=None,
            n_frames=100,
            num_keypoints=3,
            keypoint_names=['kp0', 'kp1', 'kp2'],
            image_height=150,
            image_width=200,
            video_dir=tmp_path / 'videos',
            has_videos=False,
        )
        args = self._make_args(tmp_path)
        with (
            patch(
                'lightning_pose.utils.recommender.analyze_dataset', return_value=analysis
            ),
            patch('lightning_pose.utils.recommender.get_gpu_info', return_value=None),
            patch(
                'lightning_pose.cli.commands.recommend._ask_top_down_freely_moving',
                return_value=False,
            ),
        ):
            handle(args)

        output_path = tmp_path / 'config.yaml'
        assert output_path.exists()
        content = output_path.read_text()
        assert 'generated by `litpose recommend`' in content
        assert 'backbone: vits_dino' in content
