"""Recommend command for the lightning-pose CLI."""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def register_parser(subparsers: Any) -> argparse.ArgumentParser:
    """Register the recommend command parser."""
    from textwrap import dedent

    description_text = dedent(
        """\
            Analyzes a lightning-pose dataset and prints config recommendations.

            Unlabeled videos are assumed to live in ``<dataset_path>/videos``.  A complete,
            ready-to-use config YAML is always written; use ``--output`` to control where, or
            ``--print_only`` to skip writing a file entirely.
            """
    )

    recommend_parser = subparsers.add_parser(
        'recommend',
        description=description_text,
        usage='litpose recommend <dataset_path> [--output OUTPUT | --print_only]',
    )
    recommend_parser.add_argument(
        'dataset_path',
        type=Path,
        help='directory containing one or more label CSV files (auto-discovered; multiple '
        'CSVs are treated as a multi-view dataset), or a single label CSV file',
    )
    output_group = recommend_parser.add_mutually_exclusive_group()
    output_group.add_argument(
        '--output',
        type=Path,
        default=None,
        help='path to write the recommended config YAML. a directory writes config.yaml '
        'inside it. defaults to <dataset_path>/config.yaml, or a timestamped filename if '
        'that already exists.',
    )
    output_group.add_argument(
        '--print_only',
        action='store_true',
        help='print the recommendation report only; do not write a config YAML.',
    )
    return recommend_parser


def get_parser() -> argparse.ArgumentParser:
    """Return an ArgumentParser for the `litpose recommend` subcommand (for docs)."""
    parser = argparse.ArgumentParser(prog='litpose')
    subparsers = parser.add_subparsers(dest='command')
    return register_parser(subparsers)


def _ask_top_down_freely_moving() -> bool:
    """Interactively ask whether the dataset is a top-down view of a freely moving animal.

    Returns False without prompting when stdin is not an interactive terminal.
    """
    if not sys.stdin.isatty():
        return False
    answer = input(
        'Does your dataset have a top-down view with a freely moving animal? [y/N]: '
    )
    return answer.strip().lower() in ('y', 'yes')


def _resolve_output_path(dataset_path: Path, output: Path | None) -> Path:
    """determine where to write the recommended config yaml"""
    base_dir = dataset_path if dataset_path.is_dir() else dataset_path.parent
    if output is None:
        candidate = base_dir / 'config.yaml'
        if candidate.exists():
            candidate = base_dir / f'config_{datetime.now():%Y%m%d_%H%M%S}.yaml'
        return candidate
    if output.is_dir():
        return output / 'config.yaml'
    return output


def handle(args: argparse.Namespace) -> None:
    """Handle the recommend command."""
    from omegaconf import OmegaConf

    from lightning_pose.utils import recommender

    analysis = recommender.analyze_dataset(args.dataset_path)
    gpu = recommender.get_gpu_info()
    top_down_freely_moving = _ask_top_down_freely_moving()
    rec = recommender.recommend(analysis, gpu, top_down_freely_moving=top_down_freely_moving)

    logger.info(recommender.format_report(rec, analysis, gpu))

    if args.print_only:
        return

    output_path = _resolve_output_path(args.dataset_path, args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    header = '\n'.join(
        ['# generated by `litpose recommend`; rationale for each recommended field:']
        + [f'# {name}: {reason}' for name, reason in rec.rationale.items()]
    )
    cfg = recommender.build_config(rec, analysis)
    with open(output_path, 'w') as f:
        f.write(header + '\n\n')
        f.write(OmegaConf.to_yaml(cfg))

    logger.info(f'\nwrote config to {output_path}')
